package com.timetable.timetable.entity;

import com.timetable.user.entity.User;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "timetable")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Timetable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @Setter // user는 바꿀 수도 있으니 setter 허용
    private User user;

    @Setter
    private int year;

    @Setter
    private int semester;

    @Setter
    private String name; // 시간표 이름

    @Setter
    private int totalCredits;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @OneToMany(mappedBy = "timetable",
            cascade = CascadeType.ALL,
            orphanRemoval = true)
    @Builder.Default
    @Setter(AccessLevel.NONE)  // 컬렉션은 setter 금지 (통째로 교체 못하게)
    private List<TimetableItem> items = new ArrayList<>();

    // ===== 연관관계 편의 메서드 =====

    /**
     * 시간표에 아이템 추가 (양방향 연관관계 세팅)
     */
    public void addItem(TimetableItem item) {
        this.items.add(item);
        item.setTimetable(this);
    }

    /**
     * 시간표에서 아이템 제거 (양방향 연관관계 정리)
     */
    public void removeItem(TimetableItem item) {
        this.items.remove(item);
        item.setTimetable(null);
    }

    /**
     * 고정강의만 남기고 자동 생성된 강의만 제거하고 싶을 때 사용
     */
    public void removeAutoGeneratedItems() {
        // 예: TimetableItem에 isFixed(boolean) 필드가 있다고 가정
        items.removeIf(item -> !item.isFixed());
    }

    // createdAt 자동 세팅
    @PrePersist
    public void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }
    }
}
